language: python

python:
  - "2.7"

before_install:
  - wget https://sourceforge.net/projects/devkitpro/files/Automated%20Installer/devkitARMupdate.pl
  - export DEVKITPRO=/home/travis/devkitPro
  - export DEVKITARM=${DEVKITPRO}/devkitARM
  - export PATH=$PATH:$DEVKITARM/bin

install:
  - sudo perl devkitARMupdate.pl

script:
  - python exp.py

after_success:
  - ./deploy.sh

env:
  global:
  - ENCRYPTION_LABEL: "3df26cf223a2"
  - COMMIT_AUTHOR_EMAIL: "travis@example.com"
